# -*- coding: utf-8 -*-
"""Dockcode solutions Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19CD5OiUdMn-Dv2_m37VQuT4FutAd2QEy
"""

def print_grid(rows, cols):
    hex_top =     "___     "
    hex_middle = "/   \___"
    hex_bottom = "\___/   "

    for r in range(rows):
        # Print the top part of the hexagons
        if r % 2 == 0:
            print(" " + hex_top * cols)
        else:
            print("  " + hex_top * cols)

        # Print the middle part of the hexagons
        for c in range(cols):
            if r % 2 == 0:
                print(hex_middle, end="")
            else:
                print(" " + hex_middle, end="")
        print()

        # Print the bottom part of the hexagons
        for c in range(cols):
            if r % 2 == 0:
                print(hex_bottom, end="")
            else:
                print(" " + hex_bottom, end="")
        print()


print("inputs :: 4 7")
print_grid(4, 7)

print("\ninputs :: 3 5")
print_grid(3, 5)

